"""
Core module for BookWriterAI.

This module provides the foundational components:
- Configuration management
- LLM client abstraction
- Base agent class
- Exception hierarchy
"""

from src.core.config import (
    Config,
    LLMConfig,
    BookConfig,
    ContentGenerationConfig,
    KnowledgeBaseConfig,
    NarrativeMemoryConfig,
    CharacterConfig,
    StyleConfig,
    QualityConfig,
    EmotionalArcConfig,
    GenreTemplateConfig,
    ScientificConfig,
    OutputConfig,
    Provider,
    ContentType,
    OutputFormat,
    create_config,
)
from src.core.exceptions import (
    BookWriterError,
    ConfigurationError,
    MissingAPIKeyError,
    InvalidProviderError,
    LLMError,
    LLMConnectionError,
    LLMRateLimitError,
    LLMResponseError,
    TokenBudgetExceededError,
    ContentError,
    ContentValidationError,
    ContentTooShortError,
    ContentTooLongError,
    QualityThresholdError,
    NarrativeError,
    NarrativeConsistencyError,
    EntityNotFoundError,
    EventConflictError,
    CharacterError,
    CharacterConsistencyError,
    CharacterNotFoundError,
    StyleError,
    StyleValidationError,
    KnowledgeBaseError,
    DocumentLoadError,
    DocumentParseError,
    RetrievalError,
    CheckpointError,
    CheckpointCorruptedError,
    CheckpointNotFoundError,
    GenerationError,
    OutlineGenerationError,
    ChapterGenerationError,
    BookLengthError,
    GenreError,
    GenreNotFoundError,
    GenreConventionViolationError,
)
from src.core.llm_client import (
    BaseLLMClient,
    OpenAIClient,
    QwenNativeClient,
    LLMClientFactory,
    LLMResponse,
    count_tokens,
    estimate_cost,
)
from src.core.base_agent import (
    BaseAgent,
    AgentRegistry,
    KnowledgeAwareMixin,
    NarrativeAwareMixin,
    StyleAwareMixin,
)

__all__ = [
    # Config
    "Config",
    "LLMConfig",
    "BookConfig",
    "ContentGenerationConfig",
    "KnowledgeBaseConfig",
    "NarrativeMemoryConfig",
    "CharacterConfig",
    "StyleConfig",
    "QualityConfig",
    "EmotionalArcConfig",
    "GenreTemplateConfig",
    "ScientificConfig",
    "OutputConfig",
    "Provider",
    "ContentType",
    "OutputFormat",
    "create_config",
    # Exceptions
    "BookWriterError",
    "ConfigurationError",
    "MissingAPIKeyError",
    "InvalidProviderError",
    "LLMError",
    "LLMConnectionError",
    "LLMRateLimitError",
    "LLMResponseError",
    "TokenBudgetExceededError",
    "ContentError",
    "ContentValidationError",
    "ContentTooShortError",
    "ContentTooLongError",
    "QualityThresholdError",
    "NarrativeError",
    "NarrativeConsistencyError",
    "EntityNotFoundError",
    "EventConflictError",
    "CharacterError",
    "CharacterConsistencyError",
    "CharacterNotFoundError",
    "StyleError",
    "StyleValidationError",
    "KnowledgeBaseError",
    "DocumentLoadError",
    "DocumentParseError",
    "RetrievalError",
    "CheckpointError",
    "CheckpointCorruptedError",
    "CheckpointNotFoundError",
    "GenerationError",
    "OutlineGenerationError",
    "ChapterGenerationError",
    "BookLengthError",
    "GenreError",
    "GenreNotFoundError",
    "GenreConventionViolationError",
    # LLM Client
    "BaseLLMClient",
    "OpenAIClient",
    "QwenNativeClient",
    "LLMClientFactory",
    "LLMResponse",
    "count_tokens",
    "estimate_cost",
    # Base Agent
    "BaseAgent",
    "AgentRegistry",
    "KnowledgeAwareMixin",
    "NarrativeAwareMixin",
    "StyleAwareMixin",
]